// ================================================
// RCRC COMPUSERVICE - TRADUCCIONES (ES / EN / IT)
// ================================================

const translations = {
  es: {
    // Navegación
    'nav-products': 'Productos',
    'nav-services': 'Servicios',
    'nav-reviews': 'Reseñas',
    'nav-contact': 'Contacto',

    // Hero
    'hero-tag': 'ABIERTO AHORA · LA ROMANA, RD',
    'hero-1': 'Tecnología que',
    'hero-2': 'funciona',
    'hero-3': 'y servicio que',
    'hero-4': 'resuelve.',
    'hero-desc': 'Venta de equipos informáticos y reparación especializada en La Romana. Más de 55 reseñas reales avalan nuestro trabajo.',
    'hero-cta-1': 'Ver catálogo',
    'hero-cta-2': 'WhatsApp directo',
    'stat-1': 'Google Reviews',
    'stat-2': 'Clientes felices',
    'stat-3': 'Años de experiencia',

    // Destacados (Home)
    'dest-eyebrow': '// 01 — Destacados',
    'dest-title-1': 'Productos',
    'dest-title-2': 'disponibles',
    'dest-cta': 'Ver catálogo completo',
    'explore-title': 'Explorar todo el catálogo',
    'explore-desc': 'Búsqueda, filtros por marca, categoría, precio y más.',

    // Productos comunes
    'badge-new': 'NUEVO',
    'badge-used': 'USADO',
    'badge-pending': 'PENDIENTE',
    'badge-pending-2': 'PENDIENTE',
    'badge-pending-3': 'PENDIENTE',
    'badge-pending-4': 'PENDIENTE',
    'avail-yes': 'Disponible',
    'avail-yes-2': 'Disponible',
    'avail-no': 'Agotado',
    'price-include': 'IVA incluido',
    'price-include-2': 'Garantía 30 días',
    'ssd-desc': 'Disco sólido de alta velocidad. Mejora drásticamente el rendimiento de tu equipo.',
    'dell-desc': 'Laptop confiable con procesador Intel Core i5. Ideal para trabajo y estudio.',
    'pending-1-name': 'Laptop HP — Por definir',
    'pending-1-desc': 'Información del producto pendiente de actualización desde el panel admin.',
    'pending-2-name': 'Computadora Lenovo',
    'pending-2-desc': 'Información del producto pendiente de actualización desde el panel admin.',
    'pending-3-name': 'Monitor 24"',
    'pending-3-desc': 'Información del producto pendiente de actualización desde el panel admin.',
    'pending-4-name': 'Cargador USB-C',
    'pending-4-desc': 'Información del producto pendiente de actualización desde el panel admin.',
    'pending': 'Pendiente',
    'pending-2': 'Pendiente',
    'pending-3': 'Pendiente',
    'pending-4': 'Pendiente',

    // Servicios
    'serv-eyebrow': '// 02 — Servicio técnico',
    'serv-title-1': 'Reparación',
    'serv-title-2': 'profesional.',
    'serv-meta': '↳ Diagnóstico transparente. Cotización antes de proceder.',
    'serv-1-title': 'Formateo & Windows',
    'serv-1-desc': 'Instalación de Windows, drivers y software esencial. Tu equipo como nuevo.',
    'serv-2-title': 'Cambio de pantalla',
    'serv-2-desc': 'Reparación de pantallas dañadas en laptops. Compatible con todas las marcas.',
    'serv-3-title': 'Limpieza & mantenimiento',
    'serv-3-desc': 'Limpieza interna profunda, cambio de pasta térmica. Alarga la vida del equipo.',
    'serv-4-title': 'Recuperación de datos',
    'serv-4-desc': 'Recuperamos archivos importantes de discos dañados o formateados accidentalmente.',
    'serv-5-title': 'Cambio de batería',
    'serv-5-desc': 'Reemplazo de baterías originales y compatibles para laptops de todas las marcas.',
    'serv-6-title': 'Diagnóstico técnico',
    'serv-6-desc': 'Revisión completa de tu equipo. Te explicamos exactamente qué tiene antes de cobrar.',
    'serv-7-title': 'Reparación de placa',
    'serv-7-desc': 'Reparación a nivel de componentes en placas madre de laptops y desktops.',
    'serv-cta': 'Cotizar →',
    'serv-cta-2': 'Cotizar →',
    'serv-cta-3': 'Cotizar →',
    'serv-cta-4': 'Cotizar →',
    'serv-cta-5': 'Cotizar →',
    'serv-cta-6': 'Cotizar →',
    'serv-cta-7': 'Cotizar →',

    // Reseñas
    'rev-eyebrow': '// 03',
    'rev-sub': 'La confianza no se dice, se demuestra. Estas son palabras reales de clientes reales.',
    'rev-count': '55 reseñas verificadas',
    'rev-via': 'vía Google',
    'rev-1': 'Servicio impecable. Excelente atención, puntualidad y un ambiente muy cómodo. Cuando revisan tu equipo te explican todo en detalle. Son los MEJORES, 10/10.',
    'rev-1-name': 'Cliente verificado',
    'rev-2': 'Llevé mi laptop y diagnosticaron el problema rápido. Son muy profesionales. Erika es competente en lo que hace.',
    'rev-2-name': 'Cliente verificado',
    'rev-3': '¡Excelente servicio! Somos italianos y tuvimos un problema con la pantalla LCD del iPhone. ¡Lo arreglaron en solo una hora! Son increíbles.',
    'rev-3-name': 'Turista italiano',
    'rev-more': 'Ver todas las reseñas en Google',

    // Contacto
    'cont-eyebrow': '// 04 — Visítanos',
    'cont-title-1': 'Estamos en',
    'cont-title-2': 'La Romana.',
    'cont-addr-label': 'Dirección',
    'cont-hours-label': 'Horario',
    'day-mon': 'Lunes',
    'day-tue': 'Martes',
    'day-wed': 'Miércoles',
    'day-thu': 'Jueves',
    'day-fri': 'Viernes',
    'day-sat': 'Sábado',
    'day-sun': 'Domingo',
    'closed': 'Cerrado',

    // Footer
    'foot-about': 'Especialistas en venta y reparación de equipos informáticos en La Romana, República Dominicana. Confianza desde hace más de 10 años.',
    'foot-explore': 'Explorar',
    'foot-prod': 'Catálogo',
    'foot-serv': 'Servicios',
    'foot-rev': 'Reseñas',
    'foot-cont': 'Contacto',
    'foot-contact': 'Contacto',
    'foot-social': 'Síguenos',
    'foot-rights': 'Todos los derechos reservados',

    // Catálogo
    'cat-breadcrumb-home': 'Inicio',
    'cat-breadcrumb-current': 'Catálogo',
    'cat-title-1': 'Catálogo',
    'cat-title-2': 'completo',
    'cat-subtitle': 'Explora nuestro inventario. Usa la búsqueda, los filtros laterales y el ordenamiento para encontrar exactamente lo que necesitas.',
    'cat-search-placeholder': 'Buscar productos...',
    'cat-sort-relevance': 'Relevancia',
    'cat-sort-price-asc': 'Precio: menor a mayor',
    'cat-sort-price-desc': 'Precio: mayor a menor',
    'cat-sort-name': 'Nombre A-Z',
    'cat-sort-newest': 'Más nuevos primero',
    'cat-filter-toggle': 'Filtros',
    'cat-filter-category': 'Categoría',
    'cat-filter-brand': 'Marca',
    'cat-filter-condition': 'Condición',
    'cat-filter-availability': 'Disponibilidad',
    'cat-filter-price': 'Rango de precio (RD$)',
    'cat-filter-min': 'Mín',
    'cat-filter-max': 'Máx',
    'cat-filter-clear': 'Limpiar filtros',
    'cat-results-showing': 'Mostrando',
    'cat-results-of': 'de',
    'cat-results-products': 'productos',
    'cat-no-results-title': 'No encontramos productos',
    'cat-no-results-desc': 'Intenta cambiar los filtros o limpiar la búsqueda.',
    'cat-cond-new': 'Nuevo',
    'cat-cond-used': 'Usado',
    'cat-avail-yes': 'Disponible',
    'cat-avail-no': 'Agotado',

    // Producto detalle
    'prod-breadcrumb-home': 'Inicio',
    'prod-breadcrumb-cat': 'Catálogo',
    'prod-not-found-title': 'Producto no encontrado',
    'prod-not-found-desc': 'El producto que buscas no existe o fue removido.',
    'prod-back-catalog': '← Volver al catálogo',
    'prod-cta-whatsapp': 'Apartar por WhatsApp',
    'prod-cta-call': 'Llamar ahora',
    'prod-spec-brand': 'Marca',
    'prod-spec-category': 'Categoría',
    'prod-spec-condition': 'Condición',
    'prod-spec-warranty': 'Garantía',
    'prod-spec-availability': 'Disponibilidad',
    'prod-spec-sku': 'Código',

    // Popup WhatsApp
    'wa-popup-title': '¿Necesitas ayuda?',
    'wa-popup-msg': 'Estamos en línea. Contáctanos por WhatsApp y te respondemos al instante.',
    'wa-popup-cta': 'Chatear ahora',
  },

  en: {
    'nav-products': 'Products',
    'nav-services': 'Services',
    'nav-reviews': 'Reviews',
    'nav-contact': 'Contact',
    'hero-tag': 'OPEN NOW · LA ROMANA, DR',
    'hero-1': 'Technology that',
    'hero-2': 'works',
    'hero-3': 'and service that',
    'hero-4': 'solves.',
    'hero-desc': 'Computer sales and specialized repair in La Romana. Over 55 verified reviews back our work.',
    'hero-cta-1': 'View catalog',
    'hero-cta-2': 'WhatsApp now',
    'stat-1': 'Google Reviews',
    'stat-2': 'Happy clients',
    'stat-3': 'Years of experience',
    'dest-eyebrow': '// 01 — Featured',
    'dest-title-1': 'Products',
    'dest-title-2': 'available',
    'dest-cta': 'View full catalog',
    'explore-title': 'Explore the full catalog',
    'explore-desc': 'Search, filters by brand, category, price and more.',
    'badge-new': 'NEW',
    'badge-used': 'USED',
    'badge-pending': 'PENDING',
    'badge-pending-2': 'PENDING',
    'badge-pending-3': 'PENDING',
    'badge-pending-4': 'PENDING',
    'avail-yes': 'Available',
    'avail-yes-2': 'Available',
    'avail-no': 'Out of stock',
    'price-include': 'Tax included',
    'price-include-2': '30-day warranty',
    'ssd-desc': 'High-speed solid state drive. Dramatically improves your equipment performance.',
    'dell-desc': 'Reliable laptop with Intel Core i5 processor. Ideal for work and study.',
    'pending-1-name': 'HP Laptop — TBD',
    'pending-1-desc': 'Product information pending update from admin panel.',
    'pending-2-name': 'Lenovo Desktop',
    'pending-2-desc': 'Product information pending update from admin panel.',
    'pending-3-name': '24" Monitor',
    'pending-3-desc': 'Product information pending update from admin panel.',
    'pending-4-name': 'USB-C Charger',
    'pending-4-desc': 'Product information pending update from admin panel.',
    'pending': 'Pending', 'pending-2': 'Pending', 'pending-3': 'Pending', 'pending-4': 'Pending',
    'serv-eyebrow': '// 02 — Tech service',
    'serv-title-1': 'Professional',
    'serv-title-2': 'repair.',
    'serv-meta': '↳ Transparent diagnosis. Quote before proceeding.',
    'serv-1-title': 'Format & Windows',
    'serv-1-desc': 'Windows installation, drivers and essential software. Your equipment like new.',
    'serv-2-title': 'Screen replacement',
    'serv-2-desc': 'Repair of damaged laptop screens. Compatible with all brands.',
    'serv-3-title': 'Cleaning & maintenance',
    'serv-3-desc': 'Deep internal cleaning, thermal paste change. Extends equipment life.',
    'serv-4-title': 'Data recovery',
    'serv-4-desc': 'We recover important files from damaged or accidentally formatted drives.',
    'serv-5-title': 'Battery replacement',
    'serv-5-desc': 'Original and compatible battery replacement for laptops of all brands.',
    'serv-6-title': 'Technical diagnosis',
    'serv-6-desc': 'Complete equipment review. We tell you exactly what is wrong before charging.',
    'serv-7-title': 'Motherboard repair',
    'serv-7-desc': 'Component-level repair on laptop and desktop motherboards.',
    'serv-cta': 'Quote →', 'serv-cta-2': 'Quote →', 'serv-cta-3': 'Quote →', 'serv-cta-4': 'Quote →', 'serv-cta-5': 'Quote →', 'serv-cta-6': 'Quote →', 'serv-cta-7': 'Quote →',
    'rev-eyebrow': '// 03',
    'rev-sub': 'Trust is not said, it is demonstrated. These are real words from real customers.',
    'rev-count': '55 verified reviews',
    'rev-via': 'via Google',
    'rev-1': 'Impeccable service. Excellent attention, punctuality and a very comfortable environment. When they check your equipment they explain everything in detail. They are the BEST, 10/10.',
    'rev-1-name': 'Verified customer',
    'rev-2': 'I brought my laptop and they diagnosed the problem quickly. They are very professional. Erika is competent at what she does.',
    'rev-2-name': 'Verified customer',
    'rev-3': 'Excellent service! We are Italian and we had a problem with the LCD screen on my iPhone. They fixed it in just an hour! They are amazing.',
    'rev-3-name': 'Italian tourist',
    'rev-more': 'See all reviews on Google',
    'cont-eyebrow': '// 04 — Visit us',
    'cont-title-1': 'We are in',
    'cont-title-2': 'La Romana.',
    'cont-addr-label': 'Address',
    'cont-hours-label': 'Hours',
    'day-mon': 'Monday', 'day-tue': 'Tuesday', 'day-wed': 'Wednesday', 'day-thu': 'Thursday', 'day-fri': 'Friday', 'day-sat': 'Saturday', 'day-sun': 'Sunday',
    'closed': 'Closed',
    'foot-about': 'Computer sales and repair specialists in La Romana, Dominican Republic. Trusted for over 10 years.',
    'foot-explore': 'Explore', 'foot-prod': 'Catalog', 'foot-serv': 'Services', 'foot-rev': 'Reviews', 'foot-cont': 'Contact',
    'foot-contact': 'Contact', 'foot-social': 'Follow us', 'foot-rights': 'All rights reserved',
    'cat-breadcrumb-home': 'Home',
    'cat-breadcrumb-current': 'Catalog',
    'cat-title-1': 'Full',
    'cat-title-2': 'catalog',
    'cat-subtitle': 'Browse our inventory. Use search, side filters and sorting to find exactly what you need.',
    'cat-search-placeholder': 'Search products...',
    'cat-sort-relevance': 'Relevance',
    'cat-sort-price-asc': 'Price: low to high',
    'cat-sort-price-desc': 'Price: high to low',
    'cat-sort-name': 'Name A-Z',
    'cat-sort-newest': 'Newest first',
    'cat-filter-toggle': 'Filters',
    'cat-filter-category': 'Category',
    'cat-filter-brand': 'Brand',
    'cat-filter-condition': 'Condition',
    'cat-filter-availability': 'Availability',
    'cat-filter-price': 'Price range (RD$)',
    'cat-filter-min': 'Min',
    'cat-filter-max': 'Max',
    'cat-filter-clear': 'Clear filters',
    'cat-results-showing': 'Showing',
    'cat-results-of': 'of',
    'cat-results-products': 'products',
    'cat-no-results-title': 'No products found',
    'cat-no-results-desc': 'Try changing the filters or clearing the search.',
    'cat-cond-new': 'New', 'cat-cond-used': 'Used',
    'cat-avail-yes': 'Available', 'cat-avail-no': 'Out of stock',
    'prod-breadcrumb-home': 'Home', 'prod-breadcrumb-cat': 'Catalog',
    'prod-not-found-title': 'Product not found',
    'prod-not-found-desc': 'The product you are looking for does not exist or was removed.',
    'prod-back-catalog': '← Back to catalog',
    'prod-cta-whatsapp': 'Reserve via WhatsApp',
    'prod-cta-call': 'Call now',
    'prod-spec-brand': 'Brand',
    'prod-spec-category': 'Category',
    'prod-spec-condition': 'Condition',
    'prod-spec-warranty': 'Warranty',
    'prod-spec-availability': 'Availability',
    'prod-spec-sku': 'SKU',

    // Popup WhatsApp
    'wa-popup-title': 'Need help?',
    'wa-popup-msg': 'We\'re online. Contact us via WhatsApp and we\'ll reply right away.',
    'wa-popup-cta': 'Chat now',
  },

  it: {
    'nav-products': 'Prodotti',
    'nav-services': 'Servizi',
    'nav-reviews': 'Recensioni',
    'nav-contact': 'Contatti',
    'hero-tag': 'APERTO ORA · LA ROMANA, RD',
    'hero-1': 'Tecnologia che',
    'hero-2': 'funziona',
    'hero-3': 'e servizio che',
    'hero-4': 'risolve.',
    'hero-desc': 'Vendita di apparecchiature informatiche e riparazione specializzata a La Romana. Oltre 55 recensioni verificate confermano il nostro lavoro.',
    'hero-cta-1': 'Vedi catalogo',
    'hero-cta-2': 'WhatsApp diretto',
    'stat-1': 'Recensioni Google',
    'stat-2': 'Clienti felici',
    'stat-3': 'Anni di esperienza',
    'dest-eyebrow': '// 01 — In evidenza',
    'dest-title-1': 'Prodotti',
    'dest-title-2': 'disponibili',
    'dest-cta': 'Vedi catalogo completo',
    'explore-title': 'Esplora tutto il catalogo',
    'explore-desc': 'Ricerca, filtri per marca, categoria, prezzo e altro.',
    'badge-new': 'NUOVO',
    'badge-used': 'USATO',
    'badge-pending': 'IN ATTESA',
    'badge-pending-2': 'IN ATTESA',
    'badge-pending-3': 'IN ATTESA',
    'badge-pending-4': 'IN ATTESA',
    'avail-yes': 'Disponibile',
    'avail-yes-2': 'Disponibile',
    'avail-no': 'Esaurito',
    'price-include': 'IVA inclusa',
    'price-include-2': 'Garanzia 30 giorni',
    'ssd-desc': 'Disco SSD ad alta velocità. Migliora drasticamente le prestazioni del tuo dispositivo.',
    'dell-desc': 'Laptop affidabile con processore Intel Core i5. Ideale per lavoro e studio.',
    'pending-1-name': 'Laptop HP — Da definire',
    'pending-1-desc': 'Informazioni sul prodotto in attesa di aggiornamento dal pannello admin.',
    'pending-2-name': 'Computer Lenovo',
    'pending-2-desc': 'Informazioni sul prodotto in attesa di aggiornamento dal pannello admin.',
    'pending-3-name': 'Monitor 24"',
    'pending-3-desc': 'Informazioni sul prodotto in attesa di aggiornamento dal pannello admin.',
    'pending-4-name': 'Caricatore USB-C',
    'pending-4-desc': 'Informazioni sul prodotto in attesa di aggiornamento dal pannello admin.',
    'pending': 'In attesa', 'pending-2': 'In attesa', 'pending-3': 'In attesa', 'pending-4': 'In attesa',
    'serv-eyebrow': '// 02 — Servizio tecnico',
    'serv-title-1': 'Riparazione',
    'serv-title-2': 'professionale.',
    'serv-meta': '↳ Diagnosi trasparente. Preventivo prima di procedere.',
    'serv-1-title': 'Formattazione & Windows',
    'serv-1-desc': 'Installazione di Windows, driver e software essenziali. Il tuo dispositivo come nuovo.',
    'serv-2-title': 'Sostituzione schermo',
    'serv-2-desc': 'Riparazione di schermi laptop danneggiati. Compatibile con tutti i marchi.',
    'serv-3-title': 'Pulizia & manutenzione',
    'serv-3-desc': 'Pulizia interna profonda, sostituzione pasta termica. Allunga la vita del dispositivo.',
    'serv-4-title': 'Recupero dati',
    'serv-4-desc': 'Recuperiamo file importanti da dischi danneggiati o formattati accidentalmente.',
    'serv-5-title': 'Sostituzione batteria',
    'serv-5-desc': 'Sostituzione di batterie originali e compatibili per laptop di tutte le marche.',
    'serv-6-title': 'Diagnosi tecnica',
    'serv-6-desc': 'Revisione completa del tuo dispositivo. Ti spieghiamo esattamente cosa ha prima di addebitare.',
    'serv-7-title': 'Riparazione scheda madre',
    'serv-7-desc': 'Riparazione a livello di componenti su schede madri di laptop e desktop.',
    'serv-cta': 'Preventivo →', 'serv-cta-2': 'Preventivo →', 'serv-cta-3': 'Preventivo →', 'serv-cta-4': 'Preventivo →', 'serv-cta-5': 'Preventivo →', 'serv-cta-6': 'Preventivo →', 'serv-cta-7': 'Preventivo →',
    'rev-eyebrow': '// 03',
    'rev-sub': 'La fiducia non si dice, si dimostra. Queste sono parole reali di clienti reali.',
    'rev-count': '55 recensioni verificate',
    'rev-via': 'tramite Google',
    'rev-1': 'Servizio impeccabile. Eccellente attenzione, puntualità e un ambiente molto confortevole. Quando controllano il tuo dispositivo spiegano tutto in dettaglio. Sono i MIGLIORI, 10/10.',
    'rev-1-name': 'Cliente verificato',
    'rev-2': 'Ho portato il mio laptop e hanno diagnosticato il problema rapidamente. Sono molto professionali. Erika è competente in quello che fa.',
    'rev-2-name': 'Cliente verificato',
    'rev-3': 'Eccellente servizio! Siamo italiani e abbiamo avuto un problema con lo schermo LCD del mio iPhone. Lo hanno riparato in solo un\'ora! Sono fantastici.',
    'rev-3-name': 'Turista italiano',
    'rev-more': 'Vedi tutte le recensioni su Google',
    'cont-eyebrow': '// 04 — Visitaci',
    'cont-title-1': 'Siamo a',
    'cont-title-2': 'La Romana.',
    'cont-addr-label': 'Indirizzo',
    'cont-hours-label': 'Orari',
    'day-mon': 'Lunedì', 'day-tue': 'Martedì', 'day-wed': 'Mercoledì', 'day-thu': 'Giovedì', 'day-fri': 'Venerdì', 'day-sat': 'Sabato', 'day-sun': 'Domenica',
    'closed': 'Chiuso',
    'foot-about': 'Specialisti in vendita e riparazione di apparecchiature informatiche a La Romana, Repubblica Dominicana. Affidabilità da oltre 10 anni.',
    'foot-explore': 'Esplora', 'foot-prod': 'Catalogo', 'foot-serv': 'Servizi', 'foot-rev': 'Recensioni', 'foot-cont': 'Contatti',
    'foot-contact': 'Contatti', 'foot-social': 'Seguici', 'foot-rights': 'Tutti i diritti riservati',
    'cat-breadcrumb-home': 'Home',
    'cat-breadcrumb-current': 'Catalogo',
    'cat-title-1': 'Catalogo',
    'cat-title-2': 'completo',
    'cat-subtitle': 'Esplora il nostro inventario. Usa la ricerca, i filtri laterali e l\'ordinamento per trovare esattamente ciò che ti serve.',
    'cat-search-placeholder': 'Cerca prodotti...',
    'cat-sort-relevance': 'Rilevanza',
    'cat-sort-price-asc': 'Prezzo: dal più basso',
    'cat-sort-price-desc': 'Prezzo: dal più alto',
    'cat-sort-name': 'Nome A-Z',
    'cat-sort-newest': 'Più recenti',
    'cat-filter-toggle': 'Filtri',
    'cat-filter-category': 'Categoria',
    'cat-filter-brand': 'Marca',
    'cat-filter-condition': 'Condizione',
    'cat-filter-availability': 'Disponibilità',
    'cat-filter-price': 'Fascia di prezzo (RD$)',
    'cat-filter-min': 'Min',
    'cat-filter-max': 'Max',
    'cat-filter-clear': 'Cancella filtri',
    'cat-results-showing': 'Mostrando',
    'cat-results-of': 'di',
    'cat-results-products': 'prodotti',
    'cat-no-results-title': 'Nessun prodotto trovato',
    'cat-no-results-desc': 'Prova a modificare i filtri o cancellare la ricerca.',
    'cat-cond-new': 'Nuovo', 'cat-cond-used': 'Usato',
    'cat-avail-yes': 'Disponibile', 'cat-avail-no': 'Esaurito',
    'prod-breadcrumb-home': 'Home', 'prod-breadcrumb-cat': 'Catalogo',
    'prod-not-found-title': 'Prodotto non trovato',
    'prod-not-found-desc': 'Il prodotto che cerchi non esiste o è stato rimosso.',
    'prod-back-catalog': '← Torna al catalogo',
    'prod-cta-whatsapp': 'Prenota via WhatsApp',
    'prod-cta-call': 'Chiama ora',
    'prod-spec-brand': 'Marca',
    'prod-spec-category': 'Categoria',
    'prod-spec-condition': 'Condizione',
    'prod-spec-warranty': 'Garanzia',
    'prod-spec-availability': 'Disponibilità',
    'prod-spec-sku': 'Codice',

    // Popup WhatsApp
    'wa-popup-title': 'Hai bisogno di aiuto?',
    'wa-popup-msg': 'Siamo online. Contattaci su WhatsApp e ti risponderemo subito.',
    'wa-popup-cta': 'Chatta ora',
  }
};

// Persistir el idioma elegido
function getCurrentLang() {
  return localStorage.getItem('rcrc-lang') || 'es';
}

function setLang(lang) {
  localStorage.setItem('rcrc-lang', lang);
  document.documentElement.lang = lang;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });

  // Placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if (translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  // Update lang switch buttons
  document.querySelectorAll('.lang-switch button').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

function t(key) {
  const lang = getCurrentLang();
  return translations[lang]?.[key] || translations.es[key] || key;
}
